# %%
import os

from dotenv import load_dotenv

import roboquant as rq
from roboquant.brokers.tickerall import TickerAllBroker
from roboquant import Event, Account, Signal, Order, USD
from roboquant.common.monetary import ECBConversion
from roboquant.feeds.tickerall import TickerAllLiveFeed
from roboquant.strategies.ema_crossover import EMACrossover
from roboquant.traders._util import get_order_size
from roboquant.traders.trader import Trader

# %%
load_dotenv()

# TickerAll API key
KEY = os.environ["TICKERALL_API_KEY"]

# Your MT Broker details
MT5_SERVER = os.environ["MT5_SERVER"]
MT5_ACCOUNT = os.environ["MT5_ACCOUNT"]
MT5_PASSWORD = os.environ["MT5_PASSWORD"]

# %%
class TickerAllHedging(Trader):
    """
    This trader implements a hedging strategy using multiple EMACrossover strategies.
    It creates orders based on the signals generated by each strategy and manages positions accordingly.
    """

    def __init__(self) -> None:
        self.strategies = {"ema_short": EMACrossover(2, 5), "ema_medium": EMACrossover(5, 10), "ema_long": EMACrossover(5, 20)}
        self.order_amount = 5_000@USD
        self.last_update = None

    def print(self, account: Account):
        if account.last_update != self.last_update:
            print(80 * "=", account, sep="\n", flush=True)
            self.last_update = account.last_update

    def create_orders(self, signals : list[Signal], event: Event, account: Account) -> list[Order]:

        self.print(account)
        orders = []
        for name, strategy in self.strategies.items():
            for signal in strategy.create_signals(event):
                asset = signal.asset
                price = event.get_price(asset)
                if price is None:
                    continue
                positions = [pos for pos in account.positions if pos.get_info("comment") == name and pos.asset == asset]
                if not positions:
                    if size := get_order_size(signal, price, self.order_amount, event.time, ndigits=2):
                        orders.append(rq.Order(asset, size, info={"comment": name}))
                else:
                    for pos in positions:
                        if (pos.is_long and signal.is_sell) or (pos.is_short and signal.is_buy):
                            orders.append(pos.close_order())

        return orders


# %%
ECBConversion().register()

broker = TickerAllBroker.connect(api_key=KEY, broker="mt5", server=MT5_SERVER, account=MT5_ACCOUNT, password=MT5_PASSWORD)
feed = TickerAllLiveFeed(api_key=KEY, account_id=broker.account_id)

try:
    # Cleanup existing orders and positions
    account = broker.sync()
    orders = [order.cancel() for order in account.orders] + [pos.close_order() for pos in account.positions]
    if orders:
        broker.place_orders(orders)

    # Start a 10 minute run with the TickerAllHedging trader and subscribe to multiple assets
    feed.subscribe("BTCUSD", "EURUSD", "LTCUSD", "ADAUSD", "BNBUSD")
    tf = rq.Timeframe.next("10 minutes")
    trader = TickerAllHedging()
    rq.run(feed, strategy=None, trader=trader, broker=broker, timeframe=tf)

finally:
    feed.close()
    broker.close()
