# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-latest, macos-latest]
        python-version: ["3.11", "3.12"]
 
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
          ignore-nothing-to-cache: true
          python-version: ${{ matrix.python-version }}

    - name: Install the project
      run: uv sync --all-extras

    - name: Run ruff checking
      run: uvx ruff check

    - name: Run pyright
      run: uv run pyright tests roboquant

    - name: Run unit tests
      run: uv run --no-dev python -m unittest discover -s tests/unit

  
